# Generated by Django 3.0 on 2019-12-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='longitude coordinate')),
                ('Y', models.FloatField(help_text='longtitude coordinate')),
                ('Unique_Squirrel_ID', models.CharField(help_text='identification tag for each squirrel', max_length=100)),
                ('Shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('', '')], default='', max_length=20)),
                ('Date', models.DateField(help_text='month, day, and year (MMDDYYYY)')),
                ('Age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='', max_length=20)),
                ('Primary_Fur_Color', models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('cinnamon', 'Cinnamon'), ('', '')], default='', max_length=20)),
                ('Location', models.CharField(choices=[('adult', '"Ground Plane'), ('juvenile', 'Above Ground'), ('', '')], default='', max_length=20)),
                ('Specific_Location', models.CharField(help_text='commentary on the squirrel location', max_length=100)),
                ('Running', models.BooleanField(default=True)),
                ('Chasing', models.BooleanField(default=True)),
                ('Climbing', models.BooleanField(default=True)),
                ('Eating', models.BooleanField(default=True)),
                ('Foraging', models.BooleanField(default=True)),
                ('Other_Activities', models.CharField(help_text='describe squirrels other activities', max_length=100)),
                ('Kuks', models.BooleanField(default=True)),
                ('Quaas', models.BooleanField(default=True)),
                ('Moans', models.BooleanField(default=True)),
                ('Tail_Flags', models.BooleanField(default=True)),
                ('Tail_Twitches', models.BooleanField(default=True)),
                ('Approaches', models.BooleanField(default=True)),
                ('Indifferent', models.BooleanField(default=True)),
                ('Runs_From', models.BooleanField(default=True)),
            ],
        ),
    ]
