# Generated by Django 3.0 on 2019-12-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Location',
            field=models.CharField(choices=[('adult', 'Ground Plane'), ('juvenile', 'Above Ground'), ('', '')], default='', max_length=20),
        ),
    ]
