# Generated by Django 3.0 on 2019-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191205_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Date',
            field=models.CharField(help_text='month, day, and year (MMDDYYYY)', max_length=8),
        ),
    ]
