# Generated by Django 3.0 on 2019-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191205_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sq',
            name='X',
        ),
        migrations.RemoveField(
            model_name='sq',
            name='Y',
        ),
        migrations.AddField(
            model_name='sq',
            name='Latitude',
            field=models.FloatField(default=None, help_text='latitude coordinate'),
        ),
        migrations.AddField(
            model_name='sq',
            name='Longitude',
            field=models.FloatField(default=None, help_text='longitude coordinate'),
        ),
    ]
