# Generated by Django 3.0 on 2019-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Latitude',
            field=models.FloatField(default=None, help_text='latitude coordinate'),
        ),
    ]
