# Generated by Django 3.0 on 2019-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20191206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Approaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Climbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Foraging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Indifferent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Kuks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Moans',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Quaas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Runs_From',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Tail_Flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Tail_Twitches',
            field=models.BooleanField(default=False),
        ),
    ]
