# Generated by Django 2.2.7 on 2019-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20191206_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sq',
            name='id',
        ),
        migrations.AlterField(
            model_name='sq',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='identification tag for each squirrel', max_length=100, primary_key=True, serialize=False),
        ),
    ]
