# Generated by Django 3.0 on 2019-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0010_auto_20191207_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='', max_length=15),
        ),
    ]
