# Generated by Django 2.2.7 on 2019-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0012_auto_20191207_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Other_Activities',
            field=models.CharField(default=None, help_text='describe squirrels other activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Specific_Location',
            field=models.CharField(default=None, help_text='commentary on the squirrel location', max_length=100),
        ),
    ]
