# Generated by Django 3.0 on 2019-12-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0014_auto_20191207_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Latitude',
            field=models.FloatField(blank=True, help_text='latitude coordinate', null=True),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Longitude',
            field=models.FloatField(blank=True, help_text='longitude coordinate', null=True),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='describe squirrels other activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sq',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='commentary on the squirrel location', max_length=100, null=True),
        ),
    ]
