# Generated by Django 3.0 on 2019-12-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0015_auto_20191207_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq',
            name='Date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
